travis:
  secure:
    BINSTAR_TOKEN: KRweBBZYtr4IcjYkQfiMnXXhUf40d7qiua1e+BXt56ld4lgbYL9tTCiUfKxezzshxIZG1OU/CeOkuFNsLri0z7oiwebRzCK4qyOP6bpHf4RukIDRZC6lWfBRAW5GHfzBknqmbH3xM+gjXtT2a50x36513ZwEolr0yIa7tZWCLstpbC9AuuT7fpkKmdTFu8Ick9t8wFVDbLFPzB1DSDdTtyZXrx1dYfogeiXh2bpZVr/TpR6LjBpbV9kEe+GT3tlKMFR+8bkfxAnfpL+n3IUxwzhdyq5cYUsEey4bP3YJ+pLVO7i3oRDSmVlZ02ZDYUzvu8YOXKuIUCcJAuhROW9fKY6vPwDG1js+K0UEGscK7FE34F1O54WG0ZcNQtAshO4+Pj+iFUldjLAeWWW9UiqXyk1jrCW5bacBRvVmk6L5poWNdf3EVy3anfc1AZoT0xCbVThSoZrLHb8NHD+6oHCEkQ/Kv4KcR0TmJvb/Or6XbD0z0CCyFMRSPKlcA6zWuebqOMLdoQaDGKIc3YAaLYe+kiGNE4YrG72RCL3ayrWjB+HDLHZlX76/ePHv3SMfy3MxDSR64WPJpoyMOPDeL7Ger2e86hzLKYgsIn28qyQPVghRYJwRO/wQzT8D7IJeyzxUwj1YTA/Vq8N4ooLDK6dtWgV8eac4RNB1vaIRCWCQUYE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
